security:
    api:
        pattern: ^/api
        stateless: true
        jwt: ~

    encoders:
        App\Entity\User:
            algorithm: auto
    # Hashage des mots de passe
    password_hashers:
        App\Entity\User:
            algorithm: bcrypt
            cost: 12

    # Chargement des utilisateurs
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        login:
            pattern: ^/api/login
            stateless: true
            json_login:
                check_path: /api/login
                username_path: email
                password_path: password

        main:
            stateless: true # Indique que l'API ne maintient pas de session
            provider: app_user_provider # Utilise le bon fournisseur
            json_login: # Authentification JSON
                check_path: /api/login
                username_path: email
                password_path: password
            logout:
                path: /api/logout

    # Contrôle d'accès
    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
    # Ajoutez vos règles d'accès ici
    # - { path: ^/admin, roles: ROLE_ADMIN }
    # - { path: ^/profile, roles: ROLE_USER }
