vich_uploader:
  db_driver: orm
  mappings:
    your_entity_name:
      uri_prefix: /uploads
      upload_destination: '%kernel.project_dir%/public/uploads'
      namer: Vich\UploaderBundle\Naming\OrignameNamer